package main

// commandDescription is each command's lead paragraph, sourced from the first
// paragraph after the synopsis on docs/cli/<command>.md — the same
// docs-as-source contract as commandUsage, pinned by
// TestDescriptionMatchesTheDocsLead so help and docs cannot drift.
//
// This is the prose half the generated help never had: a summary line and an
// options table say what a command is and what it takes, but not what it
// does to your state or when to reach for its neighbour instead. The docs
// already answered both for every command; the binary just never carried it.
var commandDescription = map[string]string{
	"init":       "`init` scaffolds a starter agent: a `microagent.yaml` spec, a provider-specific `agent.py`, the shared `protocol.py`, and runnable demo requests. It turns the `minimal-agent` example into a one-command starting point. The generated project is consumed by the normal `create` / `cp` / `start` flow - `init` only writes files; it does not build or run anything.",
	"doctor":     "`doctor` reports host support for the installed host backend and the default kernel status. Run it first when something isn't working. Use `host` when you want the same information as an inspectable capability report rather than a health check.",
	"run":        "`run` is the one-shot path. It fetches the image, builds a rootfs, boots the microVM, runs `--setup` then `--exec`, prints the command's output, and removes scratch state (unless `--keep` is set). Cleanup happens on failure as well as success, so iterating on a broken image does not accumulate orphaned records. The guest's stderr and serial log are captured into the result before the disk is discarded. Use `create` instead when you want the workspace to survive - `run` is for disposable work, `create` for a named workspace you'll `start`, `connect` to, and come back to.",
	"dispatch":   "`dispatch` boots a throwaway microVM under the egress guardrails you choose and runs one command. It returns the command's result and a summary of what the task reached on the network — the mediator-written audit — then tears the workspace down.",
	"create":     "`create` builds a workspace and records it under `--state-dir`. Unlike `run`, the state survives - you can `start`, `stop`, `connect`, and `delete` it later. Use `run` for disposable one-shot work; use `create` when you'll come back to the same disk. If the default kernel is missing, `create` installs it first.",
	"start":      "`start` boots a workspace that was previously created. The workspace must exist in the state directory (default `~/.microagent/`).",
	"exec":       "`exec` runs one command through the structured exec service in a running workspace and gives you typed stdout, stderr, and an exit code - it does not use the interactive console path. Use `connect` when you want a human shell session; use `exec` when a script or agent needs the result. Command arguments after `--` are passed as argv directly; use `sh -lc` explicitly when you want shell syntax.",
	"connect":    "`connect` opens an interactive serial console for a workspace - the path for a human at a keyboard. With `--send` it writes one line to the console and prints any new output. When a script or agent needs typed stdout/stderr/exit-code results, use `exec` instead.",
	"apply":      "`apply` updates the persisted workspace manifest from a spec file. It is for small declarative changes that do not need a rootfs rebuild.",
	"supervise":  "`supervise` is a foreground host supervisor. It starts a workspace and keeps watching it while the command is running. When the workspace reaches a terminal state, the persisted restart policy decides whether `supervise` starts it again.",
	"status":     "`status` reads the state file for one workspace and prints the latest event: identity, state (`prepared`, `running`, `halted`, `quarantined`, `stopped`, `failed`), and backend. It's the single-workspace deep view; use `list` when you want one row per workspace across the whole state directory.",
	"wait":       "`wait` blocks until the workspace reaches a terminal state - `stopped`, `halted`, `failed`, `quarantined`, or `prepared` (created but never started) - then prints that state and exits. The exit code says how the run ended, so scripts follow a detached `start` without polling `status` in a loop.",
	"halt":       "`halt` is the one graceful-shutdown verb and the normal way to park a workspace: it requests a clean shutdown and records the terminal state as `halted`. The VM process exits, but the rootfs, attached disks, identity, and event timeline remain under `--state-dir`, so a later `microagent start <name>` boots the same disk state. `stop` is an alias of `halt` and behaves identically.",
	"kill":       "`kill` is the hard variant of `halt`. Use it when a graceful `halt` doesn't return within its graceful window; `halt` never escalates on its own. For a clean shutdown of a healthy workspace you intend to start again, use `halt` (or its `stop` alias) instead. The disk state survives `kill`, but nothing inside the guest gets a chance to flush or exit cleanly.",
	"pause":      "`pause` freezes a running workspace and records its state as `paused`. The VM's vCPUs stop executing, but guest memory, the workspace rootfs, attached disks, identity, and `events.json` are all preserved. The runtime process keeps running and the host-side network, port forwarding, and vsock paths stay in place, so the workspace can be resumed in place with `resume`.",
	"resume":     "`resume` thaws a `paused` workspace and records its state as `running` again. The VM's vCPUs continue executing from exactly where they were frozen, with guest memory, disk state, and the host-side network, port forwarding, and vsock paths intact. After resume, `exec`, `connect`, and `stats` work again.",
	"quarantine": "`quarantine` contains a workspace in one ordered operation. It creates a durable deny marker, freezes guest execution, severs every host-side authority path, captures evidence while the guest remains frozen, and then stops the runtime into custody. Disk state, identity, runtime state files, serial logs, events, the phase result, and the forensic capture remain available.",
	"delete":     "`delete` removes the workspace record and its on-disk artifacts (rootfs, bundles, state file). The removal is permanent - to shut a workspace down and keep it, use `halt` instead.",
	"list":       "`list` walks the state directory and prints one row per saved workspace, with name, backend, and current state. It is an inventory view, so stopped workspaces appear because their disks and state still exist. To show only running workspaces, use `ps`. For everything about one workspace - readiness, verification, network detail - use `status`.",
	"ps":         "`ps` prints the live workspace view: workspaces whose VM state is starting, running, paused, quarantined, or stopping. It does not show stopped persistent workspaces. Use `list` for the full saved-workspace inventory.",
	"logs":       "`logs` prints the captured serial console output for a workspace. It is useful for boot diagnostics and for reviewing output after an interactive `connect` session.",
	"events":     "`events` prints the recorded lifecycle events for a workspace, oldest first. Structured output also joins retained constraint, egress, broker, and secret-access records into the workspace trajectory. Most text events are state transitions (`prepared`, `starting`, `running`, `halted`, `stopped`, `quarantined`, `failed`) with their timestamp and a short detail. The lifecycle history is the same bounded `events.json` history described in State and identity. It is the history view: `status` answers what state the workspace is in now, `result` returns the guest's completion payload, and `events` shows how the workspace got here.",
	"egress":     "`egress` answers one question about a workspace: what did it try to reach on the network, and what happened to each attempt?",
	"stats":      "`stats` reports CPU, memory, and I/O for a running workspace, sampled from the host view of the backing VM monitor process (similar to how `docker stats` reads container resource accounting). CPU percent is measured across a short interval and can exceed 100% for a multi-vCPU workspace.",
	"result":     "`result` reads the guest result channel for one workspace and returns the completion payload - start/completion timestamps, exit code, stdout, stderr, and failure error when the guest reported one - separately from serial logs.",
	"cp":         "`cp` copies one regular file between the host and an offline workspace disk. It is not a sync daemon and it does not attach to a running VM - the workspace must be prepared, halted, or stopped. To get output from a running workspace, use `exec` or declared `--output` artifact paths instead.",
	"artifact":   "`artifact` reports the input bundles and output paths declared in the workspace manifest. `artifact get` retrieves a declared output artifact by name without entering the workspace. The host reads it straight off the workspace disk, so the workspace must be prepared, halted, or stopped - `artifact get` fails on a running workspace. Only declared `outputs` are retrievable by artifact name; for arbitrary file copying, use `cp`.",
	"snapshot":   "A snapshot is a full checkpoint of a workspace: guest memory, device state, and a coherent copy of the rootfs disk, taken together while the VM is paused. If the current host cannot save and restore VM memory, `snapshot create` fails with a structured error before it writes a partial checkpoint. On macOS, save and restore require a host session where Virtualization.framework permits machine-state capture.",
	"clone":      "`clone` copies a prepared, halted, or stopped workspace into a new workspace record. The target gets its own rootfs and workspace-owned disks. Runtime process state is not copied - for a running-state fork, see `create --from-snapshot`.",
	"commit":     "`commit` snapshots a stopped workspace's rootfs into a single-layer OCI image, closing the loop with the OCI→rootfs realize path used by `create`/`run`. The image is written to a local OCI image layout under `<state-dir>/images/oci`; push it to a registry with `image push` or the `--push` flag.",
	"resize":     "`resize` grows or shrinks a stopped workspace's rootfs disk in place. The workspace must be halted or stopped, and must have no snapshots - a snapshot's machine state captures device geometry, and a restore would replace the resized disk with the snapshot's own anyway. Growing extends the disk immediately; shrinking refuses when the target is smaller than the filesystem's own reported usage. For a named volume's disk, use `volume resize` instead.",
	"image":      "`image` reads the local image index. Successful workspace rootfs builds and `image pull` record the source image reference, resolved digest, platform, rootfs path, size, last-used time, and rootfs SHA-256. Before an image-store rootfs is published, microagent measures it and removes its host write bits. Workspaces receive private writable copies; the shared baseline is never attached to a guest.",
	"volume":     "A named volume is a platform-managed ext4 disk with a lifecycle independent of any one workspace. It is the in-boundary analog of a container volume: instead of hand-managing `.ext4` files and passing them with `--disk`, you create a volume once and attach it by name. The registry and backing disks live under `<state-dir>/volumes/` (`index.json` plus one `<name>.ext4` per volume).",
	"network":    "`network` reports the network mode, declared port forwards, DNS servers, routes, and IP information recorded for a workspace. The top-level `network` field comes from the persistent workspace manifest; when a workspace has a runtime state file, `runtime` shows the last network config recorded by the host supervisor.",
	"model":      "`model` manages a local content-addressed store of GGUF model files and the host model server processes that serve them. Downloaded blobs are stored under `~/.microagent/models/` by default, indexed by the HuggingFace reference used to pull them. All subcommands read and write this index; no remote state is modified by the store commands. The server commands (`serve`, `stop`, `runners`) manage long-running host model runner processes. The built-in default runner is `llama-server`, but the runner command is configurable. Pair a workspace with a served model using `run --model` for one-shots or `create --model` for a persistent pairing that every `start` re-establishes.",
	"secret":     "microagent is a secret conduit, not a store. It never owns secrets at rest: it either passes operator-owned plaintext through (loudly warned) or resolves a reference from an external secret manager, holding the value only in host process memory. There is no encrypted store, keyring, or `secret set/ls/delete`.",
	"registry":   "`registry ls` is accepted as an alias for `registry list`.",
	"rootfs":     "`rootfs build` pulls an OCI image and writes an ext4 disk image. Use it when you want to prepare a rootfs ahead of time or hand it to a workspace via `create --rootfs`; the normal `run`/`create` paths build the same rootfs for you.",
	"kernel":     "`kernel` manages the guest kernel the microVMs boot. Most users can stick with `microagent run IMAGE [COMMAND ARG...]` and let `microagent` install the latest signed kernel automatically. Use `kernel` when you need to list, check, or install a specific kernel.",
	"profiles":   "`profiles` prints the built-in workspace resource profiles. Profiles are named shortcuts for memory, CPU count, and rootfs disk size; `create`, `run`, and `start` accept `--profile <name>`. Use it when you want the exact numbers behind a profile name.",
	"serve":      "`microagent serve mcp` is the MCP client integration entry point. A client launches it as a foreground stdio subprocess; it is not a normal interactive CLI command and is not advertised in top-level help. When started directly from a terminal, the command exits with setup guidance instead of waiting for MCP frames on stdin.",
	"host":       "`host` reports what `microagent` can see on the current machine: backend, architecture, supervisor availability, kernel status, virtualization support, vsock support, and console mode. It uses the same probes as `doctor`, but is meant as an inspectable capability report rather than a health check.",
	"contract":   "`contract` prints the fields a host integration can rely on: lifecycle commands, states, readiness signals, result fields, artifact channels, operation-level durability guarantees, and persistence tiers. It also reports artifact ownership, mediation fields, verification, and the capabilities declared by each supported backend. The `backendCapabilities` field identifies declared capability support; use `microagent doctor` to determine whether those capabilities are ready on the current host. Use `contract` when you are building an agent runtime or host integration and need a JSON description of what microagent reports.",
	"perf":       "`perf` runs repeatable local measurements and reports structured results. `boot` creates disposable workspaces, waits for a guest command to complete, and reports per-iteration duration plus min/avg/max. `footprint` reports the host resident set size for the recorded backend process of a running workspace. `steady` samples that RSS over time for steady-state overhead reporting.",
	"gc":         "`gc` scans the state directory for workspaces recorded as `running` and reconciles each one against reality. If the recorded VM process is gone, or its start-time `--ttl` lifetime lease has expired, `gc` tears down the leftover process group, releases stale runtime artifacts, and records the workspace's terminal state. The stale artifacts are the port-forward and vsock listener processes, the egress mediator, and transient firewall rules and network devices. A workspace whose process is still alive and in-lease is left alone. Run `gc` when `ps` and reality disagree - after a host crash, or when a supervisor exited without cleanup. It does not delete workspace disks or identity: that is `delete`.",
}
