package workspace

import (
	"archive/tar"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/geoffbelknap/microagent/pkg/broker"
	"github.com/geoffbelknap/microagent/pkg/rootfs"
)

// The guest config disk: a raw tar stream on a small read-only block
// device, regenerated by the host for every boot. The first entry is
// run.json — the guest run config that used to be baked into the rootfs —
// and the remaining entries are the workspace's declared files, prefixed
// "files/", which guest init materializes into the live filesystem before
// anything else runs. Because the host hands each boot its own config,
// nothing per-workspace lives in the rootfs image, and the setup→final
// command transition is a host decision instead of a side effect of the
// setup script's last line.

const (
	// configDiskRunConfigName is the tar entry carrying the run config.
	configDiskRunConfigName = "run.json"
	// configDiskFilePrefix prefixes declared-file entries; the target path
	// is the entry name with the prefix replaced by "/".
	configDiskFilePrefix = "files/"
	// configDiskSizeFloor pads the disk to a stable minimum so small config
	// changes do not churn the device geometry recorded in snapshots. Both
	// supported VMMs require 512-byte-multiple backing files; tar output is
	// always a 512 multiple, and the floor is a whole MiB.
	configDiskSizeFloor = 1 << 20
)

// GuestRunConfig is the host-authoritative run config delivered to guest
// init on the config disk. Field names are the wire contract with
// cmd/microagent-guestinit's config struct.
type GuestRunConfig struct {
	Command      []string             `json:"command"`
	Mode         string               `json:"mode,omitempty"`
	Env          []string             `json:"env,omitempty"`
	Port         uint32               `json:"port"`
	ShellPort    uint16               `json:"shellPort,omitempty"`
	ExecPort     uint16               `json:"execPort,omitempty"`
	Mounts       []rootfs.Mount       `json:"mounts,omitempty"`
	HostForwards []rootfs.PortForward `json:"hostForwards,omitempty"`
	ConsoleShell string               `json:"consoleShell,omitempty"`
	// Maintenance asks guest init to serve only the shell and exec
	// channels and never run a command; delivered here rather than on the
	// kernel command line so it is part of the one per-boot config record.
	Maintenance bool `json:"maintenance,omitempty"`
}

// ConfigDiskFile returns the per-workspace config disk path, in the
// runtime directory so the confinement jail staging and the fork
// bind-mount cover it and delete/cleanup sweep it.
func ConfigDiskFile(stateDir, name string) string {
	return filepath.Join(stateDir, name, "config.disk")
}

// FilesArchivePath is the durable capture of the workspace's declared file
// contents, written once at create. Boots splice it into the config disk;
// re-reading the declared sources at start time would let host-side edits
// or deletions after create change restart behavior.
func FilesArchivePath(stateDir, name string) string {
	return filepath.Join(stateDir, "workspaces", name, "files.tar")
}

// GuestBootConfig assembles the run config for the boot the options
// describe. The phase logic mirrors what the rootfs builder used to bake:
//
//   - a maintenance boot serves channels only and runs nothing;
//   - a one-shot run executes the combined setup+exec script;
//   - a prepared workspace whose setup has not completed re-runs the setup
//     script (retry-on-failure, decided host-side);
//   - after setup, the final command is the service command
//     (managed-service), the image entrypoint/cmd (--image-command,
//     service mode), or the entrypoint;
//   - a plain prepared workspace runs nothing and falls through to the
//     console shell.
//
// An empty command falls back to the image's Entrypoint+Cmd — resolved
// here from the persisted image config — except for plain prepared
// workspaces, which suppress the image command by design.
func GuestBootConfig(opts Options) (GuestRunConfig, error) {
	cfg := GuestRunConfig{
		ShellPort:    ShellPort(opts),
		ExecPort:     ExecPort(opts),
		Mounts:       MountsForBackend(opts.Backend, opts.Disks),
		HostForwards: RootfsPortForwards(opts.Network.PortForwards),
		ConsoleShell: strings.TrimSpace(opts.ConsoleShell),
	}
	env, err := guestEnv(opts)
	if err != nil {
		return GuestRunConfig{}, err
	}
	cfg.Env = env

	if opts.MaintenanceBoot {
		cfg.Maintenance = true
		return cfg, nil
	}

	setupPending := (HasSetupCommand(opts) || strings.TrimSpace(opts.ExecCommand) != "") && !opts.SetupComplete
	switch {
	case !opts.PrepareForStart || setupPending:
		// One-shot runs and pending setup boots execute the combined
		// setup+exec script and report a result. A pure service declared
		// without setup/exec is the exception: it boots straight into the
		// service (port 0, nothing to report).
		if strings.TrimSpace(opts.ServiceCommand) != "" && !HasSetupCommand(opts) && strings.TrimSpace(opts.ExecCommand) == "" {
			cfg.Command = ShellCommand(opts.ServiceCommand)
			if opts.PrepareForStart {
				cfg.Mode = "managed-service"
			}
			return cfg, nil
		}
		cfg.Command = ShellCommand(Command(opts))
		cfg.Port = opts.ResultPort
	case strings.TrimSpace(opts.ServiceCommand) != "":
		cfg.Command = ShellCommand(opts.ServiceCommand)
		cfg.Mode = "managed-service"
	case opts.UseImageCommand:
		cfg.Mode = "service"
	case strings.TrimSpace(opts.Entrypoint) != "":
		cfg.Command = ShellCommand(opts.Entrypoint)
		cfg.Port = opts.ResultPort
	default:
		// Plain prepared workspace: no command, no image fallback — boots
		// to the console shell.
		return cfg, nil
	}

	if len(cfg.Command) == 0 {
		// Image-command fallback, resolved from the image config persisted
		// at build time.
		command := append([]string{}, opts.ImageEntrypoint...)
		command = append(command, opts.ImageCmd...)
		cfg.Command = command
	}
	return cfg, nil
}

// guestEnv merges env for the guest in the same order the rootfs builder
// used to: image env first, request env over it, broker guest env last
// (fail-closed on invalid broker config). Invalid shell names are dropped,
// matching the baked behavior.
func guestEnv(opts Options) ([]string, error) {
	merged := map[string]string{}
	for _, entry := range opts.ImageEnv {
		key, value, ok := strings.Cut(entry, "=")
		if ok && validGuestEnvName(key) {
			merged[key] = value
		}
	}
	for key, value := range opts.Env {
		if validGuestEnvName(key) {
			merged[key] = value
		}
	}
	brokers, err := normalizeEffectiveBrokers(opts)
	if err != nil {
		return nil, err
	}
	for _, bc := range brokers {
		guest := broker.GuestConfig{
			GuestListen: bc.GuestListen,
			VsockPort:   bc.VsockPort,
			Proxy:       bc.Proxy,
			BaseURL:     bc.BaseURLEnv,
		}
		merged, err = guest.MergeGuestEnvMap(merged)
		if err != nil {
			return nil, fmt.Errorf("broker guest env: %w", err)
		}
	}
	if len(merged) == 0 {
		return nil, nil
	}
	keys := make([]string, 0, len(merged))
	for key := range merged {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	out := make([]string, 0, len(keys))
	for _, key := range keys {
		out = append(out, key+"="+merged[key])
	}
	return out, nil
}

func validGuestEnvName(name string) bool {
	if name == "" {
		return false
	}
	for i, r := range name {
		switch {
		case r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z'):
		case r >= '0' && r <= '9':
			if i == 0 {
				return false
			}
		default:
			return false
		}
	}
	return true
}

// WriteFilesArchive captures the declared files' contents into the durable
// files.tar at create time. No declared files removes any stale archive.
func WriteFilesArchive(opts Options) error {
	path := FilesArchivePath(opts.StateDir, opts.Name)
	if len(opts.Files) == 0 {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)
	for _, file := range opts.Files {
		data, err := os.ReadFile(file.SourcePath)
		if err != nil {
			return fmt.Errorf("declared file %s: %w", file.Path, err)
		}
		mode, err := declaredFileMode(file)
		if err != nil {
			return err
		}
		header := &tar.Header{
			Name: configDiskFilePrefix + strings.TrimPrefix(file.Path, "/"),
			Mode: int64(mode),
			Size: int64(len(data)),
		}
		if err := tw.WriteHeader(header); err != nil {
			return err
		}
		if _, err := tw.Write(data); err != nil {
			return err
		}
	}
	if err := tw.Close(); err != nil {
		return err
	}
	return writeFileAtomic(path, buf.Bytes(), 0o600)
}

func declaredFileMode(file File) (os.FileMode, error) {
	if strings.TrimSpace(file.Mode) != "" {
		parsed, err := rootfs.ParseFileMode(file.Mode)
		if err != nil {
			return 0, fmt.Errorf("file %s mode: %w", file.Path, err)
		}
		return parsed, nil
	}
	info, err := os.Stat(file.SourcePath)
	if err != nil {
		return 0, fmt.Errorf("file src %q: %w", file.SourcePath, err)
	}
	return info.Mode().Perm() & 0o644, nil
}

// WriteConfigDisk writes the per-boot config disk for the options and
// returns its path. It is called on every Create/Run/Start immediately
// before the vmkit request is built — the one point where the effective
// boot config is fully known — and skipped for snapshot restores, whose
// restored copy is authoritative.
func WriteConfigDisk(opts Options) (string, error) {
	return writeConfigDisk(opts, "config_disk_write")
}

func writeConfigDisk(opts Options, trigger string) (string, error) {
	cfg, err := GuestBootConfig(opts)
	if err != nil {
		return "", err
	}
	runConfig, err := json.Marshal(cfg)
	if err != nil {
		return "", err
	}
	runConfig = append(runConfig, '\n')

	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)
	if err := tw.WriteHeader(&tar.Header{
		Name: configDiskRunConfigName,
		Mode: 0o600,
		Size: int64(len(runConfig)),
	}); err != nil {
		return "", err
	}
	if _, err := tw.Write(runConfig); err != nil {
		return "", err
	}
	if err := spliceFilesArchive(tw, FilesArchivePath(opts.StateDir, opts.Name)); err != nil {
		return "", err
	}
	if err := tw.Close(); err != nil {
		return "", err
	}
	payload := buf.Bytes()
	if len(payload) < configDiskSizeFloor {
		payload = append(payload, make([]byte, configDiskSizeFloor-len(payload))...)
	}

	path := ConfigDiskFile(opts.StateDir, opts.Name)
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return "", err
	}
	previous, existed, err := readConstraintCurrent(path)
	if err != nil {
		return "", err
	}
	if err := writeFileAtomic(path, payload, 0o600); err != nil {
		return "", err
	}
	var manifest *Manifest
	if current, err := ReadManifest(opts.StateDir, opts.Name); err == nil {
		manifest = &current
	} else if os.IsNotExist(err) {
		initial := manifestFromOptions(opts)
		manifest = &initial
	} else if !os.IsNotExist(err) {
		return "", err
	}
	if err := appendConstraintRevision(opts, trigger, manifest); err != nil {
		if rollbackErr := rollbackConstraintCurrent(path, previous, existed); rollbackErr != nil {
			return "", fmt.Errorf("record constraint revision: %v (rollback config disk: %w)", err, rollbackErr)
		}
		return "", err
	}
	return path, nil
}

// spliceFilesArchive appends every entry of the create-time files archive
// to the config-disk tar. A missing archive means no declared files.
func spliceFilesArchive(tw *tar.Writer, archivePath string) error {
	source, err := os.Open(archivePath)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	defer func() { _ = source.Close() }()
	tr := tar.NewReader(source)
	for {
		header, err := tr.Next()
		if errors.Is(err, io.EOF) {
			return nil
		}
		if err != nil {
			return fmt.Errorf("read files archive: %w", err)
		}
		if err := tw.WriteHeader(header); err != nil {
			return err
		}
		if _, err := io.Copy(tw, tr); err != nil {
			return err
		}
	}
}

func writeFileAtomic(path string, data []byte, mode os.FileMode) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".pending-"+filepath.Base(path)+"-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer func() { _ = os.Remove(tmpPath) }()
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpPath, path)
}
